npm install -g @angular/cli
npm install -g babel-cli
npm install -g bower
npm install -g cordova
npm install -g create-react-app
npm install -g express-generator
npm install -g foundation-cli
npm install -g generator-server-configs
npm install -g generator-webapp
npm install -g github-email
npm install -g grunt
npm install -g gulp
npm install -g ionic
npm install -g isogram
npm install -g lighthouse
npm install -g npm-check
npm install -g postcss-cli
npm install -g psi
npm install -g react-devtools
npm install -g react-native-cli
npm install -g tslint
npm install -g typescript
npm install -g vue-cli
npm install -g webpack
npm install -g webpack-dev-server
npm install -g yo
